# 1. Read the Dataset 

In [1]:
import pandas as pd
import numpy as np
import datetime
pd.set_option('display.max_colwidth',None)

In [2]:
df = pd.read_csv("datasets/NLP/companies_data.csv")
df.head()

companyName  \
0              Traton SE   
1           2G Energy AG   
2    MTU Aero Engines AG   
3  Deutsche Lufthansa AG   
4      Siemens Energy AG   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             description  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.  
1                                                                                                        2G Energy AG, together with its subsidiaries, develops, manufactures, and installs combined heat and power (CHP) systems, and other systems for the recovery of electrical energy in Germany and internationally. It offers decentralized power and heat through gas motors driven by natural gas, biomethane, biogas, sewage gas, landfill gas, or hydrogen with an electrical output of 20 to 4,500 kW. The company's products include g-box, a natural gas CHP plant with the electrical output of

In [3]:
df.shape

(190, 2)

# 2. Text Preprocessing

## 2.1 Punctuation Removal

In [4]:
import string

In [5]:
def remove_punctuation(text):
    punctuationFree = "".join([i for i in text if i not in string.punctuation])
    return punctuationFree

df["puncFree"] = df['description'].apply(lambda x:remove_punctuation(x))
df['companyName'] = df['companyName'].apply(lambda x:remove_punctuation(x))

df.head(1)

companyName  \
0   Traton SE   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA

## 2.2 Lowercasing

In [6]:
df["lowercased"] = df["puncFree"].apply(lambda x: x.lower())
df['companyName'] = df['companyName'].apply(lambda x: x.lower())
df.head(1)

companyName  \
0   traton se   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  
0  traton se manufactures 

## 2.3 Tokenization

In [7]:
import re

In [8]:
def tokenization(text):
    tokens = re.split("\W+",text)
    return tokens

df["tokenized"] = df["lowercased"].apply(lambda x: tokenization(x))
df['companyName'] = df['companyName'].apply(lambda x: tokenization(x))
df.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  \
0  traton se manufactur

## 2.4 Stop-Word Removal

In [9]:
import nltk

In [10]:
# nltk.download()

In [11]:
stopWords = nltk.corpus.stopwords.words('english')
stopWords[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [12]:
def remove_stopwords(text):
    output = [i for i in text if i not in stopWords]
    return output

df["no_stop_words"] = df["tokenized"].apply(lambda x: remove_stopwords(x))
df['companyName'] = df['companyName'].apply(lambda x: remove_stopwords(x))
df.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  \
0  traton se manufactur

## 2.5 Lemmatization 

In [13]:
from nltk.stem import WordNetLemmatizer

In [14]:
wordnet_lemmatizer = WordNetLemmatizer()
def lemmatizer(text):
    lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
    return lemm_text

df['lemmatized'] = df['no_stop_words'].apply(lambda x:lemmatizer(x))
df['companyName'] = df['companyName'].apply(lambda x: lemmatizer(x))
df.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  \
0  traton se manufactur

In [15]:
df_new = df.copy()
df_new = df_new.drop(columns=['description','puncFree','lowercased','tokenized','no_stop_words'])
df_new.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          lemmatized  
0  [traton, se, manufacture, commercial, vehicle, worldwide, operates, industrial, business, financial, service, segment, company, offer, light, heavyduty, commercial, vehicle, truck, bus, chassis, van, construction, vehicle, city, bus, intercity, travel, coach, well, spare, part, service, also, provides, cloudbased, platform, freight, transportation, rio, brand, name, company, offer, product, service, man, scania, navistar, volkswagen, caminhões, e, ônibus, brand, addition, provides, range, financial, solution, including, dealer, customer, finance, leasing, insurance, product, company, founded, 2015, based, munich, germany, traton, se, subsidiary, volkswagen, finance, luxemburg, sa]

In [16]:
# df_new.to_csv("datasets/NLP/FinalDataset.csv")
# df_new = pd.read_csv("datasets/NLP/FinalDataset.csv")
# df_new.head(1)

# 3. Prepare the Data for Training

## 3.1 Data Spliting

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(df_new['lemmatized'], df_new['companyName'],
                                                   test_size=0.1, random_state=0)

# x_train, x_test, y_train, y_test = train_test_split(df_new['lemmatized'], df_new['companyName'])

In [19]:
y_train

131    [heidelberger, druckmaschinen, aktiengesellschaft]
56                                       [ringmetall, se]
101                     [müller, die, lila, logistik, ag]
134                                    [osram, licht, ag]
180                            [kuka, aktiengesellschaft]
                              ...                        
103                           [baywa, aktiengesellschaft]
67              [khd, humboldt, wedag, international, ag]
117                        [rational, aktiengesellschaft]
47                                      [technotrans, se]
172                                 [dvs, technology, ag]
Name: companyName, Length: 171, dtype: object

## 3.2 Update the internal Vocabulary

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer

# x_train = df_new['lemmatized']
# y_train = df_new['companyName']
#Tokenize the sentences
tokenizer_x_train = Tokenizer()
#Updates internal vocabulary based on a list of texts.
tokenizer_x_train.fit_on_texts(x_train)

tokenizer_y_train = Tokenizer()
tokenizer_y_train.word_index = tokenizer_x_train.word_index

first2pairs = {k: tokenizer_x_train.word_index[k] for k in list(tokenizer_x_train.word_index)[:10]}
first2pairs

2023-08-25 18:17:11.129621: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-25 18:17:11.147166: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-25 18:17:11.235725: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-25 18:17:11.236494: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-25 18:17:11.866517: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

{'company': 1,
 'system': 2,
 'service': 3,
 'segment': 4,
 'solution': 5,
 'germany': 6,
 'provides': 7,
 'ag': 8,
 'offer': 9,
 'product': 10}

In [21]:
y_tok = {k: tokenizer_y_train.word_index[k] for k in list(tokenizer_y_train.word_index)[:10]}
y_tok

{'company': 1,
 'system': 2,
 'service': 3,
 'segment': 4,
 'solution': 5,
 'germany': 6,
 'provides': 7,
 'ag': 8,
 'offer': 9,
 'product': 10}

In [22]:
len(list(tokenizer_x_train.word_index))

2746

In [23]:
len(list(tokenizer_y_train.word_index))

2746

## 3.3 Sequencing and Padding

In [24]:
from tensorflow.keras.utils import pad_sequences

#Transforms each text in texts to a sequence of integers.
x_train_seq = tokenizer_x_train.texts_to_sequences(x_train)
y_train_seq = tokenizer_y_train.texts_to_sequences(y_train)

#Pads sequences to the same length.
x_train_pad = pad_sequences(x_train_seq, padding='post')
y_train_pad = pad_sequences(y_train_seq, padding='post', maxlen=197)


x_train_pad

array([[ 348,  349,   26, ...,    0,    0,    0],
       [ 702,   30,   22, ...,    0,    0,    0],
       [1856,  901,  707, ...,    0,    0,    0],
       ...,
       [ 594,   26,   62, ...,    0,    0,    0],
       [ 866,   30,   13, ...,    0,    0,    0],
       [1280,   12,    8, ...,    0,    0,    0]], dtype=int32)

In [25]:
len(x_train_seq)

171

In [26]:
# x_train_seq

In [27]:
len(y_train_seq)

171

In [28]:
# y_train_seq

In [29]:
x_train_pad

array([[ 348,  349,   26, ...,    0,    0,    0],
       [ 702,   30,   22, ...,    0,    0,    0],
       [1856,  901,  707, ...,    0,    0,    0],
       ...,
       [ 594,   26,   62, ...,    0,    0,    0],
       [ 866,   30,   13, ...,    0,    0,    0],
       [1280,   12,    8, ...,    0,    0,    0]], dtype=int32)

In [30]:
x_train_pad[0].size

197

In [31]:
y_train_pad

array([[ 348,  349,   26, ...,    0,    0,    0],
       [ 702,   30,    0, ...,    0,    0,    0],
       [1856,  901,  707, ...,    0,    0,    0],
       ...,
       [ 594,   26,    0, ...,    0,    0,    0],
       [ 866,   30,    0, ...,    0,    0,    0],
       [1280,   12,    8, ...,    0,    0,    0]], dtype=int32)

In [32]:
y_train_pad[0].size

197

In [33]:
type(x_train_pad)

numpy.ndarray

## 3.4 Create Attention Mask

In [34]:
import tensorflow as tf

# Function to create attention masks
def create_attention_mask(sequences):
    attention_masks = tf.math.not_equal(sequences, 0)
    return tf.cast(attention_masks, dtype=tf.int32)

# Create attention masks for both x_train_pad and y_train_pad
x_train_attention_mask = create_attention_mask(x_train_pad).numpy()
y_train_attention_mask = create_attention_mask(y_train_pad).numpy()

# Print the attention masks for verification
print("x_train_attention_mask:")
print(x_train_attention_mask)

print("\ny_train_attention_mask:")
print(y_train_attention_mask[0])


x_train_attention_mask:
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]]

y_train_attention_mask:
[1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0]


2023-08-25 18:17:18.274218: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [35]:
# x_train_attention_mask = x_train_attention_mask.numpy()

In [36]:
type(x_train_attention_mask)

numpy.ndarray

In [37]:
# import numpy as np

# Shift input sequences one step to the right to create targets
y_train_pad_shift = np.roll(y_train_pad, shift=-1, axis=1)

# Shift attention masks one step to the right for targets
y_train_attention_mask_shift = np.roll(y_train_attention_mask, shift=-1, axis=1)


In [38]:
x_input = {
    "token_ids": x_train_pad,
    "padding_mask": x_train_attention_mask,
}


target_data = {
    "reverse_embedding": y_train_pad_shift,
}

# 4. Create the ML Model

In [39]:
import os
import keras_nlp
import keras_core as keras
import time
# os.environ["KERAS_BACKEND"] = "tensorflow"

Using TensorFlow backend


In [40]:
# model = keras_nlp.models.GPT2CausalLM.backbone(
#     vocabulary_size=50257,
#     num_layers=12,
#     num_heads=12,
#     hidden_dim=2478,
#     intermediate_dim=3072,
#     max_sequence_length=128,
# )

In [41]:
backbone = keras_nlp.models.GPT2Backbone(
    vocabulary_size=50257,
    num_layers=12,
    num_heads=12,
    hidden_dim=2478,
    intermediate_dim=3072,
    max_sequence_length=197,
)

In [42]:
# model.summary()

In [43]:
model = keras_nlp.models.GPT2CausalLM(backbone=backbone, preprocessor=None)

In [44]:
model.summary()

Model: "gpt2_causal_lm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                                  ┃ Output Shape                           ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ padding_mask (InputLayer)                     │ (None, None)                           │               0 │
├───────────────────────────────────────────────┼────────────────────────────────────────┼─────────────────┤
│ token_ids (InputLayer)                        │ (None, None)                           │               0 │
├───────────────────────────────────────────────┼────────────────────────────────────────┼─────────────────┤
│ gpt2_backbone (GPT2Backbone)                  │ (None, None, 2478)                     │     602,061,792 │
├───────────────────────────────────────────────┼────────────────────────────────────────┼─────────────────┤
│ reverse_embedding (ReverseEmbedding)          │ (None, None, 50257)                    │     124,536,846 │
└───────────────────────────────────────────────┴────────────────────────────────────────┴─────────────────┘

 Total params: 602,061,792 (17.94 GB)

 Trainable params: 602,061,792 (17.94 GB)

 Non-trainable params: 0 (0.00 B)

In [45]:
[print(i.shape, i.dtype) for i in model.inputs]

(None, None) <dtype: 'int32'>
(None, None) <dtype: 'int32'>


[None, None]

# 5. Train the Model

In [46]:
x = x_input
y = y_train_pad_shift
num_epochs = 1
sw = y_train_attention_mask_shift


loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=loss,
    weighted_metrics=["accuracy"])

# Save the model weights
model_path = "datasets/weights/gpt2_weights"+str(datetime.datetime.now())
model.save_weights(model_path)


model.fit(x=x, y=y, epochs=num_epochs, batch_size=2, sample_weight=sw)
# model.fit(x=x, y=y, epochs=num_epochs)

2023-08-25 18:17:23.816966: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_3' with dtype int32 and shape [171,197]
	 [[{{node Placeholder/_3}}]]
/home/wondermary/anaconda3/envs/NLP2/lib/python3.11/site-packages/tensorflow/python/framework/indexed_slices.py:459: UserWarning: Converting sparse IndexedSlices to a dense Tensor with 124536846 elements. This may consume a large amount of memory.
  warnings.warn(
2023-08-25 18:17:35.166376: I tensorflow/compiler/xla/service/service.cc:169] XLA service 0x7f747c028640 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-08-25 18:17:35.166401: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Host, Default Version
2023-08-25 18:17:35.628951: W tensorflow/compiler/tf2xla/kernels/ra

85/86 [============================>.] - ETA: 5s - loss: 0.0052 - accuracy: 0.0000e+00 

2023-08-25 18:25:23.492282: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:38] Ignoring Assert operator sparse_categorical_crossentropy/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal_1/Assert/Assert


86/86 [==============================] - 510s 5s/step - loss: 0.0052 - accuracy: 0.0000e+00


# 6. Inference

In [62]:
import tensorflow as tf

# # Load the saved model weights
model_path = "datasets/weights/gpt2_weights2023-08-25 14:41:58.141187"
model.load_weights(model_path)

# Example prompt and parameters
prompt = "Siemens company system service segment solution Germany AG provides offer product"
# prompt = "Siemens"
# prompt = "Deutsche Post AG operates as a company that deliver mail and packet. Its service and solution provide "
max_length = 400

# Tokenize the prompt
prompt_seq = tokenizer_x_train.texts_to_sequences([prompt])
prompt_pad = pad_sequences(prompt_seq, padding='post', maxlen=197)

# Create attention mask for the prompt
prompt_attention_mask = create_attention_mask(prompt_pad).numpy()

# Prepare input for the GPT-2 model
prompt_input = {
    "token_ids": prompt_pad,
    "padding_mask": prompt_attention_mask,
}

# Convert the prompt input to a tf.data.Dataset
prompt_dataset = tf.data.Dataset.from_tensor_slices(prompt_input)
prompt_dataset = prompt_dataset.batch(1)  # Batch size of 1 since we have a single prompt

# Generate text using the GPT-2 model
generated_texts = []

for prompt_batch in prompt_dataset:
    generated_ids = model.generate(prompt_batch, max_length=max_length)
    generated_text = tokenizer_x_train.sequences_to_texts(generated_ids['token_ids'])[0]
    generated_texts.append(generated_text)

# Print the generated text with appropriate formatting
for idx, generated_text in enumerate(generated_texts):
    print(f"Generated text {idx + 1}:\n{generated_text}\n")


2023-08-25 18:34:36.321193: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype int32 and shape [1,197]
	 [[{{node Placeholder/_1}}]]


Generated text 1:
siemens company system service segment solution germany ag provides offer product directly 31 satellitetosatellite covering satellitetosatellite covering brazing brazing covering satellitetosatellite covering brazing brazing satellitetosatellite covering covering satellitetosatellite covering covering satellitetosatellite satellitetosatellite satellitetosatellite satellitetosatellite satellitetosatellite satellitetosatellite covering satellitetosatellite covering covering covering covering brazing covering satellitetosatellite brazing brazing covering 31 satellitetosatellite 31 abrasive satellitetosatellite covering covering brazing covering satellitetosatellite satellitetosatellite abrasive covering



In [63]:
import tensorflow as tf

# # Load the saved model weights
model_path = "datasets/weights/gpt2_weights2023-08-25 14:41:58.141187"
model.load_weights(model_path)

# Example prompt and parameters
# prompt = "Siemens company system service segment solution Germany AG provides offer product"
prompt = "Deutsche Post AG operates as a company that deliver mail and packet. Its service and solution provide "
max_length = 400

# Tokenize the prompt
prompt_seq = tokenizer_x_train.texts_to_sequences([prompt])
prompt_pad = pad_sequences(prompt_seq, padding='post', maxlen=197)

# Create attention mask for the prompt
prompt_attention_mask = create_attention_mask(prompt_pad).numpy()

# Prepare input for the GPT-2 model
prompt_input = {
    "token_ids": prompt_pad,
    "padding_mask": prompt_attention_mask,
}

# Convert the prompt input to a tf.data.Dataset
prompt_dataset = tf.data.Dataset.from_tensor_slices(prompt_input)
prompt_dataset = prompt_dataset.batch(1)  # Batch size of 1 since we have a single prompt

# Generate text using the GPT-2 model
generated_texts = []

for prompt_batch in prompt_dataset:
    generated_ids = model.generate(prompt_batch, max_length=max_length)
    generated_text = tokenizer_x_train.sequences_to_texts(generated_ids['token_ids'])[0]
    generated_texts.append(generated_text)

# Print the generated text with appropriate formatting
for idx, generated_text in enumerate(generated_texts):
    print(f"Generated text {idx + 1}:\n{generated_text}\n")


2023-08-25 18:36:44.220572: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype int32 and shape [1,197]
	 [[{{node Placeholder/_1}}]]


Generated text 1:
deutsche post ag operates company mail service solution provide blow diagnostic covering covering estonia covering covering covering 31 covering covering 31 covering 31 covering 31 covering 31 covering covering 31 31 covering 31 31 covering covering 31 31 group 31 covering covering 31 31 31 covering



In [49]:
# # Load the saved model weights
# model_path = "datasets/weights/gpt2_weights"
# model.load_weights(model_path)

# # Example prompt and parameters
# # prompt = "Deutsche Post AG operates as a company that deliver mails and packets to "
# prompt ="Siemens company system service segment solution Germany ag provides offer product" 
# max_length = 400

# prompt_seq = tokenizer_x_train.texts_to_sequences([prompt])
# prompt_pad = pad_sequences(prompt_seq, padding='post', maxlen=197)

# def create_full_attention_mask(sequences):
#     return tf.ones_like(sequences, dtype=tf.int32)
    
# prompt_attention_mask = create_full_attention_mask(prompt_pad).numpy()


# prompt_input = {
#     "token_ids": prompt_pad,
#     "padding_mask": prompt_attention_mask,
# }


# # Generate text using the GPT-2 model
# generated_ids = model.generate(prompt_input, max_length=max_length)

# # Convert generated token IDs back to text using the appropriate tokenizer
# generated_text = tokenizer_x_train.sequences_to_texts(generated_ids['token_ids'])[0]

# # Print the generated text with appropriate formatting
# print("\nGPT-2 output:")
# print(generated_text)


In [50]:
[prompt]

['Deutsche Post AG operates as a company that deliver mail and packet. Its service and solution provide ']

In [51]:
prompt_seq

[[497, 587, 8, 13, 1, 586, 3, 5, 2123]]

In [52]:
prompt_pad

array([[ 497,  587,    8,   13,    1,  586,    3,    5, 2123,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0, 

In [53]:
prompt_pad.size

197

In [54]:
prompt_attention_mask

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)

In [55]:
prompt_attention_mask.size

197

In [56]:
prompt_input

{'token_ids': array([[ 497,  587,    8,   13,    1,  586,    3,    5, 2123,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            

In [57]:
generated_ids

{'token_ids': array([[  497,   587,     8,    13,     1,   586,     3,     5,  2123,
         25385, 25385, 21881, 28339, 28339, 17761,  5208, 47143, 50230,
         35771, 23814, 25385, 18368,  7812, 43226,  7812, 25385, 18368,
         25385, 28339,  7812,  7812, 18368, 25920, 35771,  7812, 43226,
          7812, 47143,  7812, 35771, 35771,  1791,  5208,  9321,   949,
         18625,  5989, 22581, 50230,  1791,  1791, 16487, 46202,  1791,
          1791, 46202, 13083, 39888,  1791,  5989, 18368, 22581,  1791,
         43226, 50230, 18023,  1791,  1791, 43226, 50230, 39722, 39722,
         25920, 50230, 50230, 43226, 28339, 29738, 46202, 43226, 22157,
         50230, 50230,  1791,  7267, 50230, 22581, 34971,  7267,  7219,
         36347, 22157, 22581, 44701, 48291,  1791, 48291, 37770,  7267,
         42497,  1055, 22157, 47594, 47594, 39722, 50230, 16487, 50230,
         22581, 22581,  7267, 46202, 44701, 39722, 44701,  7267, 50230,
          7267, 46202,  9474, 47594, 22581, 22581, 

In [58]:
generated_ids['token_ids'][0]

array([  497,   587,     8,    13,     1,   586,     3,     5,  2123,
       25385, 25385, 21881, 28339, 28339, 17761,  5208, 47143, 50230,
       35771, 23814, 25385, 18368,  7812, 43226,  7812, 25385, 18368,
       25385, 28339,  7812,  7812, 18368, 25920, 35771,  7812, 43226,
        7812, 47143,  7812, 35771, 35771,  1791,  5208,  9321,   949,
       18625,  5989, 22581, 50230,  1791,  1791, 16487, 46202,  1791,
        1791, 46202, 13083, 39888,  1791,  5989, 18368, 22581,  1791,
       43226, 50230, 18023,  1791,  1791, 43226, 50230, 39722, 39722,
       25920, 50230, 50230, 43226, 28339, 29738, 46202, 43226, 22157,
       50230, 50230,  1791,  7267, 50230, 22581, 34971,  7267,  7219,
       36347, 22157, 22581, 44701, 48291,  1791, 48291, 37770,  7267,
       42497,  1055, 22157, 47594, 47594, 39722, 50230, 16487, 50230,
       22581, 22581,  7267, 46202, 44701, 39722, 44701,  7267, 50230,
        7267, 46202,  9474, 47594, 22581, 22581,  7267, 32756, 22581,
       47067, 22581,

In [59]:
tokenizer_x_train.sequences_to_texts([generated_ids])[0]

''