In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth',None)

In [2]:
df = pd.read_csv("datasets/NLP/companies_data.csv")
df.head()

companyName  \
0              Traton SE   
1           2G Energy AG   
2    MTU Aero Engines AG   
3  Deutsche Lufthansa AG   
4      Siemens Energy AG   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             description  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.  
1                                                                                                        2G Energy AG, together with its subsidiaries, develops, manufactures, and installs combined heat and power (CHP) systems, and other systems for the recovery of electrical energy in Germany and internationally. It offers decentralized power and heat through gas motors driven by natural gas, biomethane, biogas, sewage gas, landfill gas, or hydrogen with an electrical output of 20 to 4,500 kW. The company's products include g-box, a natural gas CHP plant with the electrical output of

In [3]:
df.shape

(190, 2)

In [ ]:
# df.value_counts()

# Preprocessing

## Punctuation Removal

In [4]:
import string

In [5]:
def remove_punctuation(text):
    punctuationFree = "".join([i for i in text if i not in string.punctuation])
    return punctuationFree

df["puncFree"] = df['description'].apply(lambda x:remove_punctuation(x))
df['companyName'] = df['companyName'].apply(lambda x:remove_punctuation(x))

df.head(1)

companyName  \
0   Traton SE   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA

## Lowercasing

In [6]:
df["lowercased"] = df["puncFree"].apply(lambda x: x.lower())
df['companyName'] = df['companyName'].apply(lambda x: x.lower())
df.head(1)

companyName  \
0   traton se   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  
0  traton se manufactures 

## Tokenization

In [7]:
import re

In [8]:
def tokenization(text):
    tokens = re.split("\W+",text)
    return tokens

df["tokenized"] = df["lowercased"].apply(lambda x: tokenization(x))
df['companyName'] = df['companyName'].apply(lambda x: tokenization(x))
df.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  \
0  traton se manufactur

## Stop-Word Removal

In [9]:
import nltk

In [ ]:
nltk.download()

In [10]:
from nltk.corpus import brown
brown.words()

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [11]:
stopWords = nltk.corpus.stopwords.words('english')
stopWords[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [12]:
def remove_stopwords(text):
    output = [i for i in text if i not in stopWords]
    return output

df["no_stop_words"] = df["tokenized"].apply(lambda x: remove_stopwords(x))
df['companyName'] = df['companyName'].apply(lambda x: remove_stopwords(x))
df.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  \
0  traton se manufactur

## Stemming

In [13]:
from nltk.stem.porter import PorterStemmer

In [14]:
porter_stemmer = PorterStemmer()

def stemming(text):
    stem_text = [porter_stemmer.stem(word) for word in text]
    return stem_text

df['stemmed'] = df['no_stop_words'].apply(lambda x: stemming(x))
df.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  \
0  traton se manufactur

## Lemmatization 

In [15]:
from nltk.stem import WordNetLemmatizer

In [16]:
wordnet_lemmatizer = WordNetLemmatizer()

def lemmatizer(text):
    lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
    return lemm_text

df['lemmatized'] = df['no_stop_words'].apply(lambda x:lemmatizer(x))
df['companyName'] = df['companyName'].apply(lambda x: lemmatizer(x))
df.head(1)

companyName  \
0  [traton, se]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description  \
0  Traton SE manufactures commercial vehicles worldwide. It operates in Industrial Business and Financial Services segments. The company offers light and heavy-duty commercial vehicles, such as trucks and bus chassis; vans; construction vehicles; city buses; and intercity and travel coaches, as well as spare parts and services. It also provides a cloud-based platform for freight transportation under the RIO brand name. The company offers its products and services under the MAN, Scania, Navistar, and Volkswagen Caminhões e Ônibus brands. In addition, it provides a range of financial solutions, including dealer and customer finance, leasing, and insurance products. The company was founded in 2015 and is based in Munich, Germany. Traton SE is a subsidiary of Volkswagen Finance Luxemburg S.A.   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              puncFree  \
0  Traton SE manufactures commercial vehicles worldwide It operates in Industrial Business and Financial Services segments The company offers light and heavyduty commercial vehicles such as trucks and bus chassis vans construction vehicles city buses and intercity and travel coaches as well as spare parts and services It also provides a cloudbased platform for freight transportation under the RIO brand name The company offers its products and services under the MAN Scania Navistar and Volkswagen Caminhões e Ônibus brands In addition it provides a range of financial solutions including dealer and customer finance leasing and insurance products The company was founded in 2015 and is based in Munich Germany Traton SE is a subsidiary of Volkswagen Finance Luxemburg SA   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lowercased  \
0  traton se manufactur

# Model Training

In [19]:
import os

os.environ["KERAS_BACKEND"] = "tensorflow"

import keras_nlp
import tensorflow as tf
import keras_core as keras
import time

In [20]:
preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en", sequence_length=128)

gpt2_lm = keras_nlp.models.GPT2CausalLM.from_preset(
    "gpt2_base_en", preprocessor=preprocessor)

In [ ]:
start = time.time()

output = gpt2_lm.generate("how is the weather today in Kaiserslautern?",max_length=200)
print("\nGPT-2 OUTPUT:")
print(output)

end = time.time()
print(f"TOTAL TIME ELAPSED: {end - start:.2f}s")

## Vectorization / Word Embedding

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
df_new = df.copy()
df_new = df_new.drop(columns=['description','puncFree','lowercased','tokenized','no_stop_words','stemmed'])
df_new.head()

companyName  \
0               [traton, se]   
1           [2g, energy, ag]   
2    [mtu, aero, engine, ag]   
3  [deutsche, lufthansa, ag]   
4      [siemens, energy, ag]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          lemmatized  
0                                                                                                                                                                                                                                                                                  [traton, se, manufacture, commercial, vehicle, worldwide, operates, industrial, business, financial, service, segment, company, offer, light, heavyduty, commercial, vehicle, truck, bus, chassis, van, construction, vehicle, city, bus, intercity, travel, coach, well, spare, part, service, also, provides, cloudbased, platform, freight, transportation, rio, brand, name, company, offer, product, service, man, scania, navistar, volkswagen, caminhões, e, ônibus, brand, addition, provides, range, financial, solution, including, dealer, customer, finance, leasing, insurance, product, company, founded, 2015, based, munich, germany, traton, se, subsidiary, volkswagen, finance, luxemburg, sa]  
1                                                                                                                                                                                                                                              [2g, energy, ag, together, subsidiary, develops, manufacture, installs, combined, heat, power, chp, system, system, recovery, electrical, energy, germany, internationally, offer, decentralized, power, heat, gas, motor, driven, natural, gas, biomethane, biogas, sewage, gas, landfill, gas, hydrogen, electrical, output, 20, 4500, kw, company, product, include, gbox, natural, gas, chp, plant, electrical, output, 20, kw, 50, kw, aura, chp, plant, output, range, 100, kw, 420, kw, patruus, biogas, natural, gas, chp, plant, output, range, 50, kw, 263, kw, agenitor, chp, plant, capacity, 220, kw, 450, kw, avus, chp, plant, electrical, output, range, 400, kw, 4000, kw, also, engages, rental, leasing, chp, plant, company, ...]  
2                                                                                                                                          [mtu, aero, engine, ag, together, subsidiary, develops, manufacture, market, maintains, commercial, military, engine, aero, derivative, industrial, gas, turbine, germany, european, country, north, america, asia, internationally, operates, two, segment, commercial, military, engine, business, commercial, maintenance, business, company, offer, commercial, aircraft, engine, wide, body, jet, narrow, body, regional, jet, business, jet, military, aircraft, engine, fighter, aircraft, helicopter, transport, aircraft, industrial, gas, turbine, also, maintains, repair, overhaul, commercial, military, engine, manufacture, market, various, brush, seal, company, formerly, known, mtu, aero, engine, holding, ag, changed, name, mtu, aero, engine, ag, may, 2013, mtu, aero, engine, ag, found

In [23]:
df_new['lemmatized'] = df_new['lemmatized'].apply(lambda x: ','.join(map(str, x)))
df_new['companyName'] = df_new['companyName'].apply(lambda x: ','.join(map(str, x)))

In [24]:
df_new['lemmatized'].head(1)

0    traton,se,manufacture,commercial,vehicle,worldwide,operates,industrial,business,financial,service,segment,company,offer,light,heavyduty,commercial,vehicle,truck,bus,chassis,van,construction,vehicle,city,bus,intercity,travel,coach,well,spare,part,service,also,provides,cloudbased,platform,freight,transportation,rio,brand,name,company,offer,product,service,man,scania,navistar,volkswagen,caminhões,e,ônibus,brand,addition,provides,range,financial,solution,including,dealer,customer,finance,leasing,insurance,product,company,founded,2015,based,munich,germany,traton,se,subsidiary,volkswagen,finance,luxemburg,sa
Name: lemmatized, dtype: object

In [25]:
corpus = df_new['lemmatized']
countvectorizer = CountVectorizer()
x = countvectorizer.fit_transform(corpus)
result1 = x.toarray()
print(result1)

[[0 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
corpus = df_new['companyName']
countvectorizer = CountVectorizer()
x = countvectorizer.fit_transform(corpus)
result2 = x.toarray()
print(result2)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler().fit(result)
# train = scaler.transform(result)

In [ ]:
# mask = np.tile(1,(190, 2797))
# mask.shape
# mask = np.reshape(mask,(190,-1))
# mask.shape

In [ ]:
# sampleWeight = np.tile(1,(190, 2797))
# sampleWeight = np.reshape(sampleWeight,(190,-1))

In [27]:
x = df['description']
# x = {"token_ids": result1, "padding_mask": mask,}
# y = np.flip(result1)
# sw = sampleWeight
# x = result1
# y = result2
num_epochs = 1

# Linearly decaying learning rate.
# learning_rate = keras.optimizers.schedules.PolynomialDecay(
#     5e-5,
#     decay_steps=train_ds.cardinality() * num_epochs,
#     end_learning_rate=0.0,
# )
loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
gpt2_lm.compile(
    optimizer=keras.optimizers.Adam(),
    loss=loss,
    weighted_metrics=["accuracy"],
)

gpt2_lm.fit(x=x, epochs=num_epochs, batch_size=32)


2023-08-16 17:11:19.600355: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f75e80181a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-08-16 17:11:19.600392: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-08-16 17:11:20.112125: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-08-16 17:11:20.721732: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:38] Ignoring Assert operator compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal_1/Assert/Assert
2023-08-16 17:11:45.984242: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


5/6 ━━━━━━━━━━━━━━━━━━━━ 12s 12s/step - accuracy: 0.2463 - loss: 5.1825

2023-08-16 17:12:49.025157: W tensorflow/compiler/tf2xla/kernels/assert_op.cc:38] Ignoring Assert operator compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal_1/Assert/Assert


6/6 ━━━━━━━━━━━━━━━━━━━━ 142s 18s/step - accuracy: 0.2477 - loss: 5.1195


In [28]:
output1 = gpt2_lm.generate("Siemens", max_length=50)
print("\nGPT-2 output1:")
print(output1)

output2 = gpt2_lm.generate("Lufthansa", max_length=50)
print("\nGPT-2 output2:")
print(output2)


GPT-2 output1:
Siemens AG, Germany. The company also manufactures, and sells software. It manufactures and sells software solutions for software and software development software and testing. It also develops, and operates through the development, testing, and testing, testing, and

GPT-2 output2:
Lufthansa AG manufactures and sells industrial goods, such as coffee, coffee, coffee, and coffee shops, and coffee shops, as well as coffee shop services, provides coffee shops, coffee shops, and coffee shops in Germany, France
